modules:
  - name: runtime
    config:
      '@type': cosmos.app.runtime.v1alpha1.Module
      app_name: Blockchain
      begin_blockers:
        [mint, staking, auth, bank, params, consensus, distribution, genutil]
      end_blockers:
        [mint, staking, auth, bank, params, consensus, distribution, genutil]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      '@type': cosmos.auth.module.v1.Module
      bech32_prefix: cosmos
      module_account_permissions:
        - account: fee_collector
        - account: distribution
        - account: mint
          permissions: [minter]
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
  - name: tx
    config:
      '@type': cosmos.tx.config.v1.Config
  - name: params
    config:
      '@type': cosmos.params.module.v1.Module
  - name: bank
    config:
      '@type': cosmos.bank.module.v1.Module
  - name: staking
    config:
      '@type': cosmos.staking.module.v1.Module
  - name: genutil
    config:
      '@type': cosmos.genutil.module.v1.Module
  - name: mint
    config:
      '@type': cosmos.mint.module.v1.Module
  - name: distribution
    config:
      '@type': cosmos.distribution.module.v1.Module
  - name: consensus
    config:
      '@type': cosmos.consensus.module.v1.Module
